---
name: Manage labels

on:
  push:
    branches:
      - main

jobs:
  labeler:
    name: Run Labeler
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3.5.2

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v4.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          skip-delete: true
