---
name: Manage labels

on:
  push:
    branches:
      - main
  paths:
    - ".github/labels.yml"
    - ".github/workflows/labels.yml"

jobs:
  labeler:
    name: Run Labeler
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3.5.0

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v4.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yml
          skip-delete: true
          dry-run: false
          exclude: |
            help*
            *issue
